kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sqlserver-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
  zones: asia-east2-b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: sqlserver-storage-class