apiVersion: v1
kind: Service
metadata:
  name: swing-service
  labels:
    app: swing
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: swing
  type:
    #LoadBalancer  
    NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: swing-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "swing-static-ip"
spec:
  rules:
  - host: sw.shotel.vn
    http:
      paths:
      - backend:
          serviceName: swing-service
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: swing
        version: v1
    spec:
      containers:
      - name: swing
        image: gcr.io/formal-guru-247103/swing:latest
        volumeMounts:
        - name: secret
          mountPath: /etc/secret
        ports:
        - containerPort: 8000
      volumes:
        - name: secret
          secret:
            secretName: test-secret

